#!/bin/bash
cekV=$(hostname -I | awk '{print $1}' | cut -f2 -d ' ')
nameV=$(curl -sS https://raw.githubusercontent.com/3xplx/regIPvps/main/iplite | grep $MYIP | awk '{print $2}')
expV=$(curl -sS https://raw.githubusercontent.com/3xplx/regIPvps/main/iplite | grep $MYIP | awk '{print $3}')

DIR="/etc/load"
if [ -d "$DIR" ]; then
skip='TRUE'
else
mkdir /etc/load
fi


cat > /etc/load/secure.d << END
IP='$cekV'
UNAME='$nameV'
EXP='$expV'
END
