#!/bin/bash
cekV=$(hostname -I | awk '{print $1}' | cut -f2 -d ' ')
nameV=$(curl -sS https://raw.githubusercontent.com/3xplx/regIPvps/main/iplite | grep $cekV | awk '{print $2}')
expV=$(curl -sS https://raw.githubusercontent.com/3xplx/regIPvps/main/iplite | grep $cekV | awk '{print $3}')
verV=$( curl -sS https://raw.githubusercontent.com/kamunikan/permission/main/version  )
DIR="/etc/load"
if [ -d "$DIR" ]; then
skip='TRUE'
else
mkdir /etc/load
fi
cat > /etc/load/secure.d << END
IP='$cekV'
UNAME='$nameV'
EXP='$expV'
SCVER='$verV'
END
