#!/bin/bash
cekV=$(hostname -I | awk '{print $1}' | cut -f2 -d ' ')
nameV=$(curl -sS http://member.scvpn.me/register/ipvps | grep $cekV | awk '{print $2}')
expV=$(curl -sS http://member.scvpn.me/register/ipvps | grep $cekV | awk '{print $3}')
verV=$( curl -sS http://member.scvpn.me/register/version  )
mkdir /etc/load
cat > /etc/load/secure.d << END
IP='$cekV'
UNAME='$nameV'
EXP='$expV'
SCVER='$verV'
END
